

name: Expo Publish new
on:
  push:
    branches:
      - main
    paths:
      - frontend/App/**

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - name: Update config
        run: "mv frontend/App/app.config.js frontend/App/app.config.local.js"
        
      - name: Update config
        run: "mv frontend/App/app.config.azure.js frontend/App/app.config.js"
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: cd frontend/App && npm install
      - run: cd frontend/App && expo publish
